# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ko-KR" # 한국말로 설정

reviews:
  profile: "assertive"
  high_level_summary: true
  auto_review:
    enabled: true
  poem: false
chat:
  auto_reply: true
